## Numpy

https://numpy.org/doc/stable/

https://numpy.org/doc/stable/user/absolute_beginners.html

In [1]:
import numpy as np

### Numpy Arrays

In [2]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [3]:
x.dtype

dtype('int32')

In [4]:
y = np.array([1.,2,3,4])
y

array([1., 2., 3., 4.])

In [5]:
y.dtype

dtype('float64')

In [6]:
z = np.array([1.,2,3,4], dtype=int)
z

array([1, 2, 3, 4])

#### Shape and Dimension

In [7]:
x = np.zeros(6)
x

array([0., 0., 0., 0., 0., 0.])

In [8]:
x.shape

(6,)

In [9]:
x.reshape(6,1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

When using `reshape()`, we can simply put in one argument, and let Python  compute the other argument for us by putting in `-1`. 

In [10]:
x.reshape(-1,1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [11]:
y = np.ones(6)
y

array([1., 1., 1., 1., 1., 1.])

In [12]:
y.reshape(2,-1)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
y = y.reshape(-1,3)
y

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
y.shape

(2, 3)

#### Creating Arrays

In [15]:
x = np.linspace(0,10,5)
x

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
y = np.empty(10)
y

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [17]:
z = np.empty((2,3), dtype='int')
z

array([[-592871392,        499,          0],
       [         0,          1,        499]])

In [18]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
x.dtype

dtype('int32')

In [20]:
y = np.array([[1.,2,3],[4,5,6]])
y

array([[1., 2., 3.],
       [4., 5., 6.]])

In [21]:
y.dtype

dtype('float64')

Create random arrays by sampling from $N(0,1)$.

In [22]:
np.random.seed(123)  # fix random seed
A = np.random.randn(3, 4)
A

array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654, -2.42667924, -0.42891263],
       [ 1.26593626, -0.8667404 , -0.67888615, -0.09470897]])

#### Array Slicing

In [23]:
A[:,0]

array([-1.0856306 , -0.57860025,  1.26593626])

In [24]:
A[0,:]

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471])

In [25]:
A[:,1:]

array([[ 0.99734545,  0.2829785 , -1.50629471],
       [ 1.65143654, -2.42667924, -0.42891263],
       [-0.8667404 , -0.67888615, -0.09470897]])

In [26]:
A[1:3, 2:4]

array([[-2.42667924, -0.42891263],
       [-0.67888615, -0.09470897]])

#### Array Methods

In [27]:
a = np.array([4,3,2,1.])
a

array([4., 3., 2., 1.])

In [28]:
a.sort()
a

array([1., 2., 3., 4.])

In [29]:
a.sum()

10.0

In [30]:
a.cumsum()

array([ 1.,  3.,  6., 10.])

In [31]:
y

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
y.sum()

21.0

In [33]:
y.sum(axis=0)

array([5., 7., 9.])

In [34]:
y.sum(axis=1)

array([ 6., 15.])

In [35]:
y.mean()

3.5

In [36]:
y.std()

1.707825127659933

In [37]:
y.var()

2.9166666666666665

In [38]:
y.argmax()

5

In [39]:
y.shape

(2, 3)

In [40]:
y.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

Alternatively, we can do the following.

In [41]:
np.sum(y)

21.0

In [42]:
np.sum(y, axis=0)

array([5., 7., 9.])

In [43]:
np.mean(y, axis=1)

array([2., 5.])

In [44]:
np.std(y, axis=0)

array([1.5, 1.5, 1.5])

### Arithmetic Operations

The operators `+, -, *, /` and `**` all act elementwise on arrays

In [45]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a + b

array([ 6,  8, 10, 12])

In [46]:
a * b

array([ 5, 12, 21, 32])

In [47]:
a + 10

array([11, 12, 13, 14])

In [48]:
a * 10

array([10, 20, 30, 40])

In [49]:
A = np.ones((2, 2))
B = np.ones((2, 2))
A + B

array([[2., 2.],
       [2., 2.]])

In [50]:
A

array([[1., 1.],
       [1., 1.]])

In [51]:
B

array([[1., 1.],
       [1., 1.]])

In [52]:
A + 10

array([[11., 11.],
       [11., 11.]])

In [53]:
A * B

array([[1., 1.],
       [1., 1.]])

### Matrix Multiplication

One can use the `@` symbol for matrix multiplication, as follows:

In [54]:
A = np.array([[1,2],[3,4.]])
B = np.array([[4,3],[2,1.]])

A @ B

array([[ 8.,  5.],
       [20., 13.]])

In [55]:
A = np.array((1, 2))
B = np.array((10, 20))

A @ B

50

### Broadcasting

In element-wise operations, arrays may not have the same shape.

When this happens, NumPy will automatically expand arrays to the same shape whenever possible.

This useful (but sometimes confusing) feature in NumPy is called **broadcasting**.

In [56]:
a = np.array(
        [[1, 2, 3], 
         [4, 5, 6], 
         [7, 8, 9]])

b = np.array([3, 6, 9])

a + b

array([[ 4,  8, 12],
       [ 7, 11, 15],
       [10, 14, 18]])

In [57]:
a * b

array([[ 3, 12, 27],
       [12, 30, 54],
       [21, 48, 81]])

In [58]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
b

array([3, 6, 9])

In [60]:
a + b.reshape(-1,1)

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [61]:
a * b.reshape(-1,1)

array([[ 3,  6,  9],
       [24, 30, 36],
       [63, 72, 81]])

In [62]:
a = np.array([3, 6, 9])
b = np.array([2, 3, 4])

a + b.reshape(-1,1)

array([[ 5,  8, 11],
       [ 6,  9, 12],
       [ 7, 10, 13]])

In [63]:
a * b.reshape(-1,1)

array([[ 6, 12, 18],
       [ 9, 18, 27],
       [12, 24, 36]])

In [64]:
a = np.array(
      [[1, 2],
       [4, 5],
       [7, 8]])
b = np.array([3, 6, 9])

a + b

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [65]:
a * b

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

### Mutability and Copying Arrays

NumPy arrays are mutable data types, like Python lists.

In other words, their contents can be altered (mutated) in memory after initialization.

In [66]:
a = np.array([1.,2])
a

array([1., 2.])

In [67]:
b = a

In [68]:
b[1] = 5
b

array([1., 5.])

In [69]:
a

array([1., 5.])

In [70]:
c = np.copy(a)
c[1] = 9
c

array([1., 9.])

In [71]:
a

array([1., 5.])